"""Canonical Web Research vocabulary."""

from enum import StrEnum


class ResearchMode(StrEnum):
    NO_RESEARCH = "NO_RESEARCH"
    SEARCH = "SEARCH"
    FETCH = "FETCH"
    MULTI_SOURCE_RESEARCH = "MULTI_SOURCE_RESEARCH"


class ResearchErrorCode(StrEnum):
    DISABLED = "RESEARCH_DISABLED"
    POLICY_DENIED = "RESEARCH_POLICY_DENIED"
    PERMISSION_REQUIRED = "RESEARCH_PERMISSION_REQUIRED"
    CONFIRMATION_REQUIRED = "RESEARCH_CONFIRMATION_REQUIRED"
    PROVIDER_UNAVAILABLE = "RESEARCH_PROVIDER_UNAVAILABLE"
    RATE_LIMITED = "RESEARCH_RATE_LIMITED"
    SEARCH_TIMEOUT = "RESEARCH_SEARCH_TIMEOUT"
    FETCH_TIMEOUT = "RESEARCH_FETCH_TIMEOUT"
    BLOCKED_URL = "RESEARCH_BLOCKED_URL"
    DNS_REBINDING = "RESEARCH_DNS_REBINDING"
    UNSUPPORTED_CONTENT = "RESEARCH_UNSUPPORTED_CONTENT"
    CONTENT_TOO_LARGE = "RESEARCH_CONTENT_TOO_LARGE"
    EXTRACTION_FAILED = "RESEARCH_EXTRACTION_FAILED"
    INSUFFICIENT_EVIDENCE = "RESEARCH_INSUFFICIENT_EVIDENCE"
    CITATION_INTEGRITY = "RESEARCH_CITATION_INTEGRITY"
    MALFORMED_SYNTHESIS = "RESEARCH_MALFORMED_SYNTHESIS"
