"""Shared validated vocabulary for Phase 2 authority decisions."""

from enum import IntEnum, StrEnum


class RiskLevel(IntEnum):
    NEGLIGIBLE = 0
    LOW = 1
    MODERATE = 2
    ELEVATED = 3
    HIGH = 4
    CRITICAL = 5


class PermissionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"


class ConfirmationPolicy(StrEnum):
    NEVER = "NEVER"
    ONCE = "ONCE"
    EVERY_TIME = "EVERY_TIME"
    HIGH_RISK_ONLY = "HIGH_RISK_ONLY"


class PermissionGrantSource(StrEnum):
    USER_EXPLICIT = "USER_EXPLICIT"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"
    MIGRATION = "MIGRATION"


class AuthorizationDecisionType(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_CONFIRMATION = "REQUIRE_CONFIRMATION"


class DecisionReason(StrEnum):
    AUTHORIZED = "AUTHORIZED"
    NO_PERMISSION = "NO_PERMISSION"
    PERMISSION_REVOKED = "PERMISSION_REVOKED"
    PERMISSION_EXPIRED = "PERMISSION_EXPIRED"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    DEVICE_SCOPE_MISMATCH = "DEVICE_SCOPE_MISMATCH"
    DEVICE_REVOKED = "DEVICE_REVOKED"
    CAPABILITY_DISABLED = "CAPABILITY_DISABLED"
    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    CONFIRMATION_EXPIRED = "CONFIRMATION_EXPIRED"
    CONFIRMATION_REJECTED = "CONFIRMATION_REJECTED"
    CONFIRMATION_MISMATCH = "CONFIRMATION_MISMATCH"
    CONFIRMATION_REPLAYED = "CONFIRMATION_REPLAYED"
    RISK_TOO_HIGH = "RISK_TOO_HIGH"
    FINANCIAL_EXECUTION_BLOCKED = "FINANCIAL_EXECUTION_BLOCKED"
    USER_DISABLED = "USER_DISABLED"
    INVALID_IDENTITY = "INVALID_IDENTITY"
    AUTHORIZATION_EVALUATION_FAILED = "AUTHORIZATION_EVALUATION_FAILED"


class ConfirmationStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AI = "AI"
    AUTOMATION = "AUTOMATION"
    DEVICE = "DEVICE"


class AuditEventType(StrEnum):
    PERMISSION_GRANTED = "PERMISSION_GRANTED"
    PERMISSION_REVOKED = "PERMISSION_REVOKED"
    PERMISSION_EXPIRED_OBSERVED = "PERMISSION_EXPIRED_OBSERVED"
    AUTHORIZATION_ALLOWED = "AUTHORIZATION_ALLOWED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    CONFIRMATION_REQUESTED = "CONFIRMATION_REQUESTED"
    CONFIRMATION_APPROVED = "CONFIRMATION_APPROVED"
    CONFIRMATION_REJECTED = "CONFIRMATION_REJECTED"
    FINANCIAL_GUARD_TRIGGERED = "FINANCIAL_GUARD_TRIGGERED"
    TASK_CREATED = "TASK_CREATED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_CLAIMED = "TASK_CLAIMED"
    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_ARCHIVED = "MEMORY_ARCHIVED"
    MEMORY_DELETED = "MEMORY_DELETED"
    AI_ROUTING_DENIED = "AI_ROUTING_DENIED"
    ORCHESTRATION_DENIED = "ORCHESTRATION_DENIED"
    ORCHESTRATION_CONFIRMATION_REQUIRED = "ORCHESTRATION_CONFIRMATION_REQUIRED"
    ORCHESTRATION_READY = "ORCHESTRATION_READY"
    ORCHESTRATION_SECURITY_REJECTED = "ORCHESTRATION_SECURITY_REJECTED"
    ORCHESTRATION_CANCELLED = "ORCHESTRATION_CANCELLED"


class AuditResult(StrEnum):
    RECORDED = "RECORDED"
    ALLOWED = "ALLOWED"
    DENIED = "DENIED"
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
