"""Server-owned Orchestrator vocabulary with no authority-bearing client flags."""

from enum import StrEnum


class IntentCategory(StrEnum):
    INFORMATIONAL = "INFORMATIONAL"
    MEMORY = "MEMORY"
    ACTION = "ACTION"
    DESTRUCTIVE = "DESTRUCTIVE"
    UNSUPPORTED = "UNSUPPORTED"


class OrchestrationState(StrEnum):
    RECEIVED = "RECEIVED"
    CONTEXT_PREPARED = "CONTEXT_PREPARED"
    ROUTED = "ROUTED"
    PROPOSAL_GENERATED = "PROPOSAL_GENERATED"
    PLAN_VALIDATED = "PLAN_VALIDATED"
    WAITING_PERMISSION = "WAITING_PERMISSION"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    READY_FOR_EXECUTION = "READY_FOR_EXECUTION"
    COMPLETED_NO_ACTION = "COMPLETED_NO_ACTION"
    DENIED = "DENIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class OrchestrationStepType(StrEnum):
    RECEIVED = "RECEIVED"
    CONTEXT_SELECTED = "CONTEXT_SELECTED"
    AI_ROUTED = "AI_ROUTED"
    PROPOSAL_VALIDATED = "PROPOSAL_VALIDATED"
    TASK_LINKED = "TASK_LINKED"
    AUTHORITY_BLOCKED = "AUTHORITY_BLOCKED"
    EXECUTION_ENVELOPE_CREATED = "EXECUTION_ENVELOPE_CREATED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"


class OrchestrationReason(StrEnum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    CONTEXT_READY = "CONTEXT_READY"
    ROUTING_SELECTED = "ROUTING_SELECTED"
    INFORMATIONAL_COMPLETE = "INFORMATIONAL_COMPLETE"
    PLAN_VALID = "PLAN_VALID"
    UNSUPPORTED_INTENT = "UNSUPPORTED_INTENT"
    INVALID_MODEL_PROPOSAL = "INVALID_MODEL_PROPOSAL"
    PLAN_INTEGRITY_FAILURE = "PLAN_INTEGRITY_FAILURE"
    INVALID_CAPABILITY_ACTION = "INVALID_CAPABILITY_ACTION"
    PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    FINANCIAL_EXECUTION_PROHIBITED = "FINANCIAL_EXECUTION_PROHIBITED"
    SENSITIVITY_ROUTING_DENIED = "SENSITIVITY_ROUTING_DENIED"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    SAFE_MODE_BLOCKED = "SAFE_MODE_BLOCKED"
    MAINTENANCE_BLOCKED = "MAINTENANCE_BLOCKED"
    TASK_CANCELLED = "TASK_CANCELLED"
    WORKFLOW_EXPIRED = "WORKFLOW_EXPIRED"
    READY_FOR_FUTURE_EXECUTION = "READY_FOR_FUTURE_EXECUTION"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"


class SafeMode(StrEnum):
    NORMAL = "NORMAL"
    SAFE_MODE = "SAFE_MODE"
    MAINTENANCE = "MAINTENANCE"


class SideEffectClass(StrEnum):
    NONE = "NONE"
    READ_ONLY = "READ_ONLY"
    EXTERNAL = "EXTERNAL"
    DESTRUCTIVE = "DESTRUCTIVE"
    FINANCIAL = "FINANCIAL"


class OrchestrationActor(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
