"""Canonical Text Assistant vocabulary without authority-bearing client flags."""

from enum import StrEnum


class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"


class MessageStatus(StrEnum):
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AssistantIntent(StrEnum):
    CHAT = "CHAT"
    MEMORY_SAVE = "MEMORY_SAVE"
    MEMORY_RECALL = "MEMORY_RECALL"
    MEMORY_DELETE = "MEMORY_DELETE"
    ACTION = "ACTION"
    RESEARCH = "RESEARCH"


class AssistantOutcome(StrEnum):
    ANSWERED = "ANSWERED"
    MEMORY_SAVED = "MEMORY_SAVED"
    MEMORY_RECALLED = "MEMORY_RECALLED"
    MEMORY_PERMISSION_REQUIRED = "MEMORY_PERMISSION_REQUIRED"
    MEMORY_TARGET_REQUIRED = "MEMORY_TARGET_REQUIRED"
    MEMORY_CONFIRMATION_REQUIRED = "MEMORY_CONFIRMATION_REQUIRED"
    MEMORY_DELETED = "MEMORY_DELETED"
    ACTION_WAITING_PERMISSION = "ACTION_WAITING_PERMISSION"
    ACTION_WAITING_CONFIRMATION = "ACTION_WAITING_CONFIRMATION"
    ACTION_READY_FOR_FUTURE_EXECUTION = "ACTION_READY_FOR_FUTURE_EXECUTION"
    ACTION_DENIED = "ACTION_DENIED"
    ACTION_UNSUPPORTED = "ACTION_UNSUPPORTED"
    RESEARCH_ANSWERED = "RESEARCH_ANSWERED"
    RESEARCH_PERMISSION_REQUIRED = "RESEARCH_PERMISSION_REQUIRED"
    RESEARCH_CONFIRMATION_REQUIRED = "RESEARCH_CONFIRMATION_REQUIRED"
    RESEARCH_POLICY_DENIED = "RESEARCH_POLICY_DENIED"
    RESEARCH_UNAVAILABLE = "RESEARCH_UNAVAILABLE"
    RESEARCH_INSUFFICIENT_EVIDENCE = "RESEARCH_INSUFFICIENT_EVIDENCE"
    FAILED = "FAILED"


class AssistantFailureReason(StrEnum):
    AI_ROUTING_DENIED = "AI_ROUTING_DENIED"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    MEMORY_NOT_AVAILABLE = "MEMORY_NOT_AVAILABLE"
    MEMORY_TARGET_REQUIRED = "MEMORY_TARGET_REQUIRED"
    ORCHESTRATION_DENIED = "ORCHESTRATION_DENIED"
    EXECUTOR_UNAVAILABLE = "EXECUTOR_UNAVAILABLE"
