"""Canonical AI Router vocabulary owned by the server."""

from enum import IntEnum, StrEnum


class ModelClass(StrEnum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    ADVANCED = "ADVANCED"
    REALTIME = "REALTIME"
    EMBEDDING = "EMBEDDING"
    LOCAL = "LOCAL"


class Complexity(StrEnum):
    TRIVIAL = "TRIVIAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class ModelCapability(StrEnum):
    TEXT_GENERATION = "TEXT_GENERATION"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    TOOL_CALLING = "TOOL_CALLING"
    STREAMING = "STREAMING"
    AUDIO_REALTIME = "AUDIO_REALTIME"
    EMBEDDINGS = "EMBEDDINGS"


class QualityTier(IntEnum):
    FAST = 1
    STANDARD = 2
    ADVANCED = 3
    SPECIALIZED = 4


class LatencyTier(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"


class ProviderHealth(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"


class FailureCategory(StrEnum):
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    CONTEXT_LIMIT = "CONTEXT_LIMIT"
    CONTENT_POLICY = "CONTENT_POLICY"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    MALFORMED_RESPONSE = "MALFORMED_RESPONSE"
    INTERNAL_PROVIDER_ERROR = "INTERNAL_PROVIDER_ERROR"
    CANCELLED = "CANCELLED"


class RoutingReason(StrEnum):
    DEFAULT_STANDARD = "DEFAULT_STANDARD"
    LOW_COMPLEXITY_FAST = "LOW_COMPLEXITY_FAST"
    HIGH_COMPLEXITY_ADVANCED = "HIGH_COMPLEXITY_ADVANCED"
    REQUIRED_CAPABILITY = "REQUIRED_CAPABILITY"
    REALTIME_REQUIRED = "REALTIME_REQUIRED"
    EMBEDDING_REQUIRED = "EMBEDDING_REQUIRED"
    LOCAL_ONLY_REQUIRED = "LOCAL_ONLY_REQUIRED"
    SENSITIVITY_RESTRICTION = "SENSITIVITY_RESTRICTION"
    CONTEXT_LIMIT = "CONTEXT_LIMIT"
    OUTPUT_LIMIT = "OUTPUT_LIMIT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    NO_ELIGIBLE_MODEL = "NO_ELIGIBLE_MODEL"
    EQUIVALENT_PROVIDER_FALLBACK = "EQUIVALENT_PROVIDER_FALLBACK"
    QUALITY_ESCALATION = "QUALITY_ESCALATION"
    COST_NEUTRAL_OPTIMIZATION = "COST_NEUTRAL_OPTIMIZATION"
    BUDGET_WARNING = "BUDGET_WARNING"
    HARD_BUDGET_EXCEEDED = "HARD_BUDGET_EXCEEDED"


class RoutingOutcome(StrEnum):
    SELECTED = "SELECTED"
    DENIED = "DENIED"


class UsageOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


RETRYABLE_FAILURES = frozenset(
    {
        FailureCategory.PROVIDER_UNAVAILABLE,
        FailureCategory.RATE_LIMITED,
        FailureCategory.TIMEOUT,
        FailureCategory.INTERNAL_PROVIDER_ERROR,
    }
)


def is_retryable_failure(category: FailureCategory) -> bool:
    """Return the centralized retry classification for provider failures."""
    return category in RETRYABLE_FAILURES
