"""Canonical Task Engine vocabulary."""

from enum import StrEnum


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    WAITING_CONNECTION = "WAITING_CONNECTION"
    WAITING_PERMISSION = "WAITING_PERMISSION"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class TaskPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskAttemptStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskEventType(StrEnum):
    CREATED = "CREATED"
    STATE_CHANGED = "STATE_CHANGED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    CLAIMED = "CLAIMED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AI = "AI"
    AUTOMATION = "AUTOMATION"
    DEVICE = "DEVICE"
    WORKER = "WORKER"


class TaskTransitionReason(StrEnum):
    CREATED_AUTHORIZED = "CREATED_AUTHORIZED"
    CREATED_WAITING_PERMISSION = "CREATED_WAITING_PERMISSION"
    CREATED_WAITING_CONFIRMATION = "CREATED_WAITING_CONFIRMATION"
    USER_CANCELLED = "USER_CANCELLED"
    DEADLINE_REACHED = "DEADLINE_REACHED"
    WORKER_CLAIMED = "WORKER_CLAIMED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    AUTHORIZATION_REEVALUATED = "AUTHORIZATION_REEVALUATED"
