"""Canonical Realtime Voice states, event kinds, and safe failures."""

from enum import StrEnum


class VoiceSessionState(StrEnum):
    IDLE = "IDLE"
    CONNECTING = "CONNECTING"
    LISTENING = "LISTENING"
    PROCESSING = "PROCESSING"
    SPEAKING = "SPEAKING"
    INTERRUPTING = "INTERRUPTING"
    RECONNECTING = "RECONNECTING"
    ENDED = "ENDED"
    FAILED = "FAILED"


class VoiceTurnStatus(StrEnum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    INTERRUPTED = "INTERRUPTED"
    FAILED = "FAILED"


class TranscriptKind(StrEnum):
    PARTIAL = "PARTIAL"
    FINAL = "FINAL"


class VoiceClientEventType(StrEnum):
    AUDIO_FRAME = "AUDIO_FRAME"
    INTERRUPT = "INTERRUPT"
    END_SESSION = "END_SESSION"
    PLAYBACK_COMPLETED = "PLAYBACK_COMPLETED"


class VoiceServerEventType(StrEnum):
    SESSION_STATE = "SESSION_STATE"
    TRANSCRIPT = "TRANSCRIPT"
    ASSISTANT_TEXT = "ASSISTANT_TEXT"
    ASSISTANT_AUDIO = "ASSISTANT_AUDIO"
    TURN_INTERRUPTED = "TURN_INTERRUPTED"
    ERROR = "ERROR"


class VoiceErrorCode(StrEnum):
    MIC_PERMISSION_DENIED = "MIC_PERMISSION_DENIED"
    AUDIO_DEVICE_UNAVAILABLE = "AUDIO_DEVICE_UNAVAILABLE"
    NETWORK_UNAVAILABLE = "NETWORK_UNAVAILABLE"
    VOICE_SESSION_AUTH_FAILED = "VOICE_SESSION_AUTH_FAILED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    REALTIME_MODEL_UNAVAILABLE = "REALTIME_MODEL_UNAVAILABLE"
    SENSITIVITY_DENIED = "SENSITIVITY_DENIED"
    CONTEXT_LIMIT = "CONTEXT_LIMIT"
    AUDIO_INPUT_FAILURE = "AUDIO_INPUT_FAILURE"
    AUDIO_OUTPUT_FAILURE = "AUDIO_OUTPUT_FAILURE"
    SESSION_TIMEOUT = "SESSION_TIMEOUT"
    RECONNECT_EXHAUSTED = "RECONNECT_EXHAUSTED"
    MALFORMED_EVENT = "MALFORMED_EVENT"
    CANCELLED = "CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
